return {
  "folke/snacks.nvim",
  opts = {
    picker = {
      sources = {
        files = {
          hidden = true,
          ignored = false,
          win = {
            input = {
              keys = {
                ["<S-h>"] = "toggle_hidden",
                ["<S-i>"] = "toggle_ignored",
                ["<S-f>"] = "toggle_follow",
              },
            },
          },
          exclude = {
            "**/.git/*",
            "**/node_modules/*",
            "**/.yarn/cache/*",
            "**/.yarn/install*",
            "**/.yarn/releases/*",
            "**/.pnpm-store/*",
            "**/.idea/*",
            "**/.DS_Store",
            "**/.venv/**",
            "build/*",
            "coverage/*",
            "dist/*",
            "hodor-types/*",
            "**/target/*",
            "**/public/*",
            "**/.node-gyp/**",
            "**/claude/debug",
            "**/claude/file-history",
            "**/claude/plans",
            "**/claude/plugins",
            "**/claude/projects",
            "**/claude/session-env",
            "**/claude/shell-snapshots",
            "**/claude/statsig",
            "**/claude/telemetry",
            "**/claude/todos",
            "**/claude/history.jsonl",
            "**/claude/*cache*",
          },
        },
        grep = {
          hidden = true,
          ignored = false,
          win = {
            input = {
              keys = {
                ["<S-h>"] = "toggle_hidden",
                ["<S-i>"] = "toggle_ignored",
                ["<S-f>"] = "toggle_follow",
              },
            },
          },
          exclude = {
            "**/.git/*",
            "**/node_modules/*",
            "**/.yarn/cache/*",
            "**/.yarn/install*",
            "**/.yarn/releases/*",
            "**/.pnpm-store/*",
            "**/.venv/*",
            "**/.idea/*",
            "**/.DS_Store",
            "**/.venv/**",
            "**/yarn.lock",
            "build*/*",
            "coverage/*",
            "dist/*",
            "certificates/*",
            "hodor-types/*",
            "**/target/*",
            "**/public/*",
            "**/digest*.txt",
            "**/.node-gyp/**",
            "**/claude/debug",
            "**/claude/file-history",
            "**/claude/plans",
            "**/claude/plugins",
            "**/claude/projects",
            "**/claude/session-env",
            "**/claude/shell-snapshots",
            "**/claude/statsig",
            "**/claude/telemetry",
            "**/claude/todos",
            "**/claude/history.jsonl",
            "**/claude/*cache*",
          },
        },
        grep_buffers = {},
        explorer = {
          hidden = true,
          ignored = false,
          supports_live = true,
          auto_close = true,
          diagnostics = true,
          diagnostics_open = false,
          focus = "list",
          follow_file = true,
          git_status = true,
          git_status_open = false,
          git_untracked = true,
          jump = { close = true },
          tree = true,
          watch = true,
          exclude = {
            -- ".git",
            ".yarn/cache/**",
            ".yarn/install/**",
            ".yarn/install*",
            ".yarn/releases/**",
            ".pnpm-store",
            ".venv",
            ".DS_Store",
            "**/.node-gyp/**",
            "**/claude/debug",
            "**/claude/file-history",
            "**/claude/plans",
            "**/claude/plugins",
            "**/claude/projects",
            "**/claude/session-env",
            "**/claude/shell-snapshots",
            "**/claude/statsig",
            "**/claude/telemetry",
            "**/claude/todos",
            "**/claude/history.jsonl",
            "**/claude/*cache*",
          },
        },
      },
    },
  },
}
